### PR TITLE
Harvester: Add pod affinity to VM config page

### PR DESCRIPTION
**Pull request by DaiYuzeng**
### Summary
Add pod affinity on VM/VM template config page
#### Create/Edit/View
image

#### Test steps
_Create VM_

1. Go to Create VM
2. Add node/pod affinity
3. Save
4. Configuration of node/pod affinity should be found in yaml
5. Go to Edit VM
6. Configuration of node/pod affinity should be accurate on UI
7. Modify the configuration of node/pod affinity
8. Save
9. Repeat step 4

_Create VM from template_
1. Go to Create VM Template
2. Add node/pod affinity
3. Save
4. Go to Edit VM Template
5. Configuration of node/pod affinity should be accurate on UI
6. Modify the configuration of node/pod affinity
7. Save
8. Go to Create VM
9. Use template what you just created
10. Save
11. Configuration of node/pod affinity should be found in yaml

### Occurred changes and/or fixed issues

- https://github.com/harvester/harvester/issues/2491
- https://github.com/harvester/harvester/issues/2317

### CODE REVIEW

**Review by n313893254 — CHANGES_REQUESTED** [review]
1. `Pod` should display as `VM` on the Harvester page.
2. The namespace list should filter, as the namespace selector do

image


Others LGTM

**Review by n313893254 — APPROVED** [review]
LGTM, considering the node driver also requires changing the pod affinity label, maybe using the label key as a prop would be a better design.

**Comment by WuJun2016** [comment]
image

**Comment by DaiYuzeng** [comment]
Upstream PR at: https://github.com/rancher/dashboard/pull/8331

**Review by WuJun2016 — APPROVED** [review]
LGTM

**Pull request merged**
