### PR TITLE
HARVESTER: delete metadata when clone volume

### PR DESCRIPTION
**Pull request by WuJun2016**
# links
- https://github.com/harvester/harvester/issues/1977

### CODE REVIEW

**Review by DaiYuzeng — COMMENTED** [review]
@WuJun2016 attached VM display correctly, but Volume's phase is lost, is it expected?

截屏2022-03-09 上午8 31 11

**Comment by WuJun2016** [comment]
> 

This is a bug, already fixed。  PTAL

**Review by DaiYuzeng — APPROVED** [review]
Tested and LGTM!

**Review by n313893254 — APPROVED** [review]
LGTM

**Pull request merged**
