### PR TITLE
Get `backendPort` as options in Health Check in Load Balance

### PR DESCRIPTION
**Pull request by torchiaf**
#### PR Checklist
- Is this a multi-tenancy feature/bug?
    - [ ] Yes, the relevant RBAC changes are at:
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
    - [ ] Yes, the relevant PR is at:
- Are backend engineers aware of UI changes?
    - [ ] Yes, the backend owner is:

Related issue https://github.com/harvester/harvester/issues/5444

### Occurred changes and/or fixed issues

The `listeners.backendPort` is used instead of `listeners.port`, when selecting the port in Health Check tab.

### Technical notes summary

- Changing the port data source
- Fixing an issue in Health Check tab: when disabling the Health Box, old fields remain filled in the Load Balancer object (and YAML).
- Adding a warning message to notice the users when a backend port in Listeners tab is used in Heath Check.

### Screenshot/Video

Backend port 5000

image

Port options in Health Check tab

image

Warning message in Listeners when port 5000 is select in Health Box

image

### CODE REVIEW

**Comment by a110605** [comment]
Test locally, LGTM. 

But nice to have adding `min/max` and `type='number'` for [backend port input](https://github.com/harvester/dashboard/blob/580679fc88c057c746065817cbd78939dd8799ee/pkg/harvester/edit/loadbalancer.harvesterhci.io.loadbalancer/Listeners.vue#L177) to avoid unexpected string / number input.

image

**Review by a110605 — APPROVED** [review]

**Review by Yu-Jack — APPROVED** [review]
LGTM, thanks.

**Comment by torchiaf** [comment]
> Nice to have adding `min/max` and `type='number'` for [backend port input](https://github.com/harvester/dashboard/blob/580679fc88c057c746065817cbd78939dd8799ee/pkg/harvester/edit/loadbalancer.harvesterhci.io.loadbalancer/Listeners.vue#L177) to avoid unexpected string / number input.
> 

Good catch! I just pushed the change, could you give it another look ?

**Review by a110605 — APPROVED** [review]
Looks good. Thanks

**Comment by torchiaf** [comment]
@mergify backport release-harvester-v1.2 release-harvester-v1.3

**Pull request merged**
