### PR TITLE
Fix multi-key shortcuts in vm console view

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary

Fixes https://github.com/harvester/harvester/issues/4535

### CODE REVIEW

**Review by markhillgit — APPROVED** [review]
lgtm thanks

**Review by bk201 — APPROVED** [review]

**Comment by torchiaf** [comment]
@Mergifyio backport v1.2

**Comment by torchiaf** [comment]
@Mergifyio backport v1.2.2

**Comment by torchiaf** [comment]
@mergify backport release-harvester-v1.2

**Pull request merged**
