### PR TITLE
Using vmimage.status.storageClassName to fill volumeClaimTemplates

### PR DESCRIPTION
**Pull request by torchiaf**
#### PR Checklist
- Is this a multi-tenancy feature/bug?
    - [ ] Yes, the relevant RBAC changes are at:
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
    - [ ] Yes, the relevant PR is at:
- Are backend engineers aware of UI changes?
    - [ ] Yes, the backend owner is:

Related issue https://github.com/harvester/harvester/issues/5551

### Technical notes summary

Populating volumeClaimTemplates with vmimage.status.storageClassName intead of `"longhorn-${imageId}"`

### CODE REVIEW

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thank you.

**Review by Yu-Jack — APPROVED** [review]
LGTM, thanks.

**Comment by FrankYang0529** [comment]
@mergify backport release-harvester-v1.3 release-harvester-v1.2

**Comment by FrankYang0529** [comment]
@mergify backport release-harvester-v1.3

**Comment by torchiaf** [comment]
@mergify backport release-harvester-v1.3

**Comment by torchiaf** [comment]
@mergify backport release-harvester-v1.3

**Pull request merged**
