### PR TITLE
Fix Node list in VMs Migrate dialog

### PR DESCRIPTION
**Pull request by torchiaf**
#### PR Checklist
- Is this a multi-tenancy feature/bug?
    - [ ] Yes, the relevant RBAC changes are at:
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
    - [ ] Yes, the relevant PR is at:
- Are backend engineers aware of UI changes?
    - [ ] Yes, the backend owner is:

Related Issue https://github.com/harvester/harvester/issues/6591

### Technical notes summary

It filters the nodes only if VM has Cpu pinning enabled.

### CODE REVIEW

**Review by w13915984028 — APPROVED** [review]
LGTM, thanks.

**Review by a110605 — APPROVED** [review]
Thanks for fixing my bug :face_with_peeking_eye:
If VM is not enabled CPU pinning, it should be able to migrate any non-witness / non-self nodes.

**Comment by a110605** [comment]
@torchiaf , @brandboat ,I add a warning banner in migration VM dialog to let user know there is a limiation that cpu pinning VM can only choose cpu manager enabled node.

Screenshot 2024-09-25 at 11 20 55 AM

**Comment by a110605** [comment]
Ｗait for https://github.com/harvester/dashboard/pull/1170 merge first.

**Review by a110605 — APPROVED** [review]
LGTM

**Comment by torchiaf** [comment]
@mergify backport release-harvester-v1.4

**Pull request merged**
