### PR TITLE
HARVESTSER: fix opensuse qga

### PR DESCRIPTION
**Pull request by WuJun2016**
# links
- https://github.com/harvester/harvester/issues/1833

### CODE REVIEW

**Review by DaiYuzeng — COMMENTED** [review]
Should we use `qemu-guest-agent.service` to instead of `qemu-guest-agent`?
截屏2022-02-11 上午10 07 20

**Comment by WuJun2016** [comment]
It should not be necessary, we use `qemu-guest-agent `instead of `qemu-ga`, and in my testing I found that` qemu-guest-agent `is equivalent to q`emu-guest-agent.service`.  But eventually I need the help of Guangbo to research it, thanks.  cc @guangbochen

**Comment by guangbochen** [comment]
`.service` is an extension of Linux's long-running background service filename, I would prefer to use `qemu-guest-agent.service` for all of them if that works, thanks.

**Review by n313893254 — APPROVED** [review]

**Review by DaiYuzeng — APPROVED** [review]
LGTM!

**Pull request merged**
