### PR TITLE
Change default eviction strategy to LiveMigrateIfPossible

### PR DESCRIPTION
**Pull request by connorkuehl**
#### PR Checklist
- Is this a multi-tenancy feature/bug?
    - [ ] Yes, the relevant RBAC changes are at:
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
    - [ ] Yes, the relevant PR is at:
- Are backend engineers aware of UI changes?
    - [x] Yes, the backend owner is: @connorkuehl 

Related issue https://github.com/harvester/harvester/issues/5495

### CODE REVIEW

**Review by torchiaf — APPROVED** [review]
LGTM.

**Comment by connorkuehl** [comment]
@torchiaf Do you prefer 2 approvals on dashboard PRs or is this good to go?

**Comment by torchiaf** [comment]
> @torchiaf Do you prefer 2 approvals on dashboard PRs or is this good to go?

@connorkuehl I added Kiefer, thanks.

**Review by bk201 — APPROVED** [review]
LGTM

**Comment by torchiaf** [comment]
@mergify backport release-harvester-v1.2 release-harvester-v1.3

**Pull request merged**
