### PR TITLE
HARVESTER: Update Chinese translation

### PR DESCRIPTION
**Pull request by vickyhella**
- HARVESTER: Update Chinese translation

### CODE REVIEW

**Comment by vickyhella** [comment]
@WuJun2016 @n313893254 Please take a look at the translation update. Thanks!

**Comment by WuJun2016** [comment]
Hi,  @vickyhella   Can you help translate this menu part ？ Otherwise, part Chinese and part English will look a little strange.  thanks
image

**Comment by vickyhella** [comment]
@WuJun2016 

1. Monitoring & Logging: The reason why they weren't translated is that `logging` and `monitoring` are the names of our plugins, so we keep them untranslated in both Rancher and Harvester UI. But I agree we can translate them here as it can be clearer and they do not necessarily mean the plugins.
I will translate it to `监控 & 日志` later.

3. *Flow: Guangbo suggested that we should keep the English version in an earlier PR (https://github.com/harvester/dashboard/pull/444#pullrequestreview-1135289137)

**Review by WuJun2016 — APPROVED** [review]
LGTM， thanks

**Comment by WuJun2016** [comment]
Hi,  @vickyhella  Can you help resubmit a copy to the `release-harvester-v1.1` branch ？

**Comment by vickyhella** [comment]
> Hi, @vickyhella Can you help resubmit a copy to the `release-harvester-v1.1` branch ？

@WuJun2016 PR submitted: https://github.com/harvester/dashboard/pull/610

**Pull request merged**
