### PR TITLE
HARVESTER: fix ksmtuned RBAC

### PR DESCRIPTION
**Pull request by WuJun2016**
### Summary
Fix cluster-member user without permission

#### PR Checklist
~- Is this a multi-tenancy feature/bug?
    - [ ] Yes, the relevant RBAC changes are at:~
~- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
    - [ ] Yes, the relevant PR is at:~
~- Are backend engineers aware of UI changes?
    - [ ] Yes, the backend owner is:~

Fixes #

### CODE REVIEW

**Review by n313893254 — COMMENTED** [review]
Seems the error is caused by ntp JSON parse, the issue is I can't close the last error notification.

The Harvester version is v1.2.0-rc2, will validate it after the rc3 release. Other LGTM

image

**Comment by WuJun2016** [comment]
> Seems the error is caused by ntp JSON parse, the issue is I can't close the last error notification.
> 
> The Harvester version is v1.2.0-rc2, will validate it after the rc3 release. Other LGTM
> 
> image

This is another issue that has been fixed： https://github.com/harvester/harvester/issues/4103

**Review by n313893254 — APPROVED** [review]
image

**Comment by n313893254** [comment]
@mergify backport release-harvester-v1.2

**Pull request merged**
