### PR TITLE
VM Restore column label

### PR DESCRIPTION
**Pull request by torchiaf**
#### PR Checklist
- Is this a multi-tenancy feature/bug?
    - [ ] Yes, the relevant RBAC changes are at:
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
    - [ ] Yes, the relevant PR is at:
- Are backend engineers aware of UI changes?
    - [ ] Yes, the backend owner is:

Related Issue https://github.com/harvester/harvester/issues/5795

### CODE REVIEW

**Review by a110605 — APPROVED** [review]
Wouldn't restore column use `tableHeaders.restore` in shell/assets/translations/en-us.yaml ?

**Comment by torchiaf** [comment]
> Wouldn't restore column use `tableHeaders.restore` in shell/assets/translations/en-us.yaml ?

I assume that Harvester loads the en-us.yaml from the Rancher built shell instead of Harvester plugin itself, but, `tableHeaders.restore` was removed from shell/assets/translations/en-us.yaml in the latest Rancher version.

**Comment by torchiaf** [comment]
@mergify backport release-harvester-v1.3

**Comment by torchiaf** [comment]
@mergify backport release-harvester-v1.4

**Pull request merged**
