### PR TITLE
Remove empty code formatted label from Host  NTP warning label

### PR DESCRIPTION
**Pull request by torchiaf**
#### PR Checklist
- Is this a multi-tenancy feature/bug?
    - [ ] Yes, the relevant RBAC changes are at:
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
    - [ ] Yes, the relevant PR is at:
- Are backend engineers aware of UI changes?
    - [ ] Yes, the backend owner is:

Related Issue https://github.com/harvester/harvester/issues/6067

### Screenshot/Video

Before

截圖 2024-06-25 下午5 03 00

After

Available NPT server name
image

Empty NPT server name
image

### CODE REVIEW

**Review by a110605 — APPROVED** [review]
LGTM

**Comment by torchiaf** [comment]
@mergify backport release-harvester-v1.2 release-harvester-v1.3

**Comment by albinsun** [comment]
Hi, I'm on `v1.2-head` and try to set an invalid NTP server `0.no.such.pool.ntp.org`.
image

Where is the message is expected to show?
Cuz I can not observe fail syncing message on
1. setting page
   image
2. host page
   image
   image

**Comment by torchiaf** [comment]
> 
> Where is the message is expected to show? Cuz I can not observe fail syncing message on
> 


@albinsun for other settings, the UI gets a webhook validation error, which is displayed as a small error dialog on top-right corner of the window.
I think ti should be the same here

**Comment by torchiaf** [comment]
@albinsun I added some notes on how to replicate the issue in the description.

**Pull request merged**
