### PR TITLE
Sort by Host Ip / I Address

### PR DESCRIPTION
**Pull request by torchiaf**
#### PR Checklist
- Is this a multi-tenancy feature/bug?
    - [ ] Yes, the relevant RBAC changes are at:
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
    - [ ] Yes, the relevant PR is at:
- Are backend engineers aware of UI changes?
    - [ ] Yes, the backend owner is:

Related Issue: https://github.com/harvester/harvester/issues/4197

### Technical notes summary

Adding sorting functionality to:

- Hosts table
- Virtual Machines table

### CODE REVIEW

**Comment by a110605** [comment]
LGTM, the IP address is sortable on virtual machine resource table.

Should we also turn `tableHeaders.hostIp` in  [pkg/harvester/detail/network.harvesterhci.io.vlanconfig.vue](https://github.com/harvester/dashboard/blob/ab3e246a89f80104546808342d0856d55e117ea3/pkg/harvester/detail/network.harvesterhci.io.vlanconfig.vue#L45) sortable ?


Screenshot 2024-04-23 at 9 44 16 AM

**Comment by a110605** [comment]
This PR can change to `ready for review`.

**Comment by torchiaf** [comment]
> LGTM, the IP address is sortable on virtual machine resource table.
> 
> Should we also turn `tableHeaders.hostIp` in [pkg/harvester/detail/network.harvesterhci.io.vlanconfig.vue](https://github.com/harvester/dashboard/blob/ab3e246a89f80104546808342d0856d55e117ea3/pkg/harvester/detail/network.harvesterhci.io.vlanconfig.vue#L45) sortable ?
> 
> Screenshot 2024-04-23 at 9 44 16 AM

It could be, what do you think @bk201 ? ATM we are adding the sortable only to the main tables: Hosts and Virtual Machines.

**Comment by bk201** [comment]
Sounds good to sort the IPs in that page too.

**Review by a110605 — APPROVED** [review]
LGTM

**Pull request merged**
