### PR TITLE
[BUG] Final edits to the UI strings

### PR DESCRIPTION
**Pull request by asettle**
1. Currently unable to chagne the message "VirtualMachine generation is 2..."
2. Discrepency between "cluster flow/flows" etc is out of my control for the UI string changes.

Closes #6407 
Issue: https://github.com/harvester/harvester/issues/6407

### CODE REVIEW

**Comment by a110605** [comment]
> Discrepency between "cluster flow/flows" etc is out of my control for the UI string changes.
You can change remove `99` in [harvesterhci.io.logging.clusterflow.vue](https://github.com/asettle/dashboard/blob/8b5dae416a846b7d58c4f22789737b3889e8a430/pkg/harvester/list/harvesterhci.io.logging.clusterflow.vue#L72) to keep `label/For` getter to use [default count = 1](https://github.com/asettle/dashboard/blob/8b5dae416a846b7d58c4f22789737b3889e8a430/shell/store/type-map.js#L426) to get typeDisplay (list page title) 

```
 return this.$store.getters['type-map/labelFor'](schema);
```
Same for harvesterhci.io.logging.clusteroutput.vue / flow.vue / output.vue

**Comment by a110605** [comment]
> Currently unable to chagne the message "VirtualMachine generation is 2..."

@Yu-Jack or @FrankYang0529 , could you help separate "virtualMachine" to "Virtual Machine" in [harvester/vendor/sigs.k8s.io/cli-utils/pkg/kstatus/status/generic.go](			message := fmt.Sprintf("%s generation is %d, but latest observed generation is %d", u.GetKind(), generation, observedGeneration))

**Comment by FrankYang0529** [comment]
> > Currently unable to chagne the message "VirtualMachine generation is 2..."
> 
> Hi @Yu-Jack or @FrankYang0529 ,
> 
> Could you kindly help separate the wording "VirtualMachine" to "Virtual Machine" in [harvester/vendor/sigs.k8s.io/cli-utils/pkg/kstatus/status/generic.go](https://github.com/harvester/harvester/blob/09fdcc538965fd0c3c4b8e2eb409b19d0b3dbdac/vendor/sigs.k8s.io/cli-utils/pkg/kstatus/status/generic.go#L90) ?
> 
> Screenshot 2024-09-26 at 2 22 47 PM

Hi @a110605, we may not be able to do that. [harvester/vendor/sigs.k8s.io/cli-utils/pkg/kstatus/status/generic.go](https://github.com/harvester/harvester/blob/09fdcc538965fd0c3c4b8e2eb409b19d0b3dbdac/vendor/sigs.k8s.io/cli-utils/pkg/kstatus/status/generic.go#L90) is upstream code. Also, [VirtualMachine](https://github.com/kubevirt/kubevirt/blob/72b9c98e597a9f0c945ed624e30c3da36bd1c3f0/staging/src/kubevirt.io/api/core/v1/register.go#L79) is defined in upstream.

**Comment by Yu-Jack** [comment]
BTW, it's a `Kind`, so it's slightly different meaning between `VirtualMachine` and `Virtual Machine`.

**Comment by a110605** [comment]
Thanks @FrankYang0529 , @Yu-Jack , looks like if we really want to separate them, we can only use replacement in vm
[stateDescription](https://github.com/harvester/dashboard/blob/f4d655c474e8d55b6afeaa9bedc806cf36130221/pkg/harvester/models/kubevirt.io.virtualmachine.js#L1072) cc @asettle 


```
 get stateDescription() {
    let stateDescription = super.stateDescription;

    if (stateDescription?.includes('VirtualMachine')) {
      stateDescription = stateDescription.replace('VirtualMachine', 'Virtual Machine');
    }

    return this.ingoreVMMessage ? '' : stateDescription;
  }

```
Screenshot 2024-09-26 at 3 54 32 PM

**Comment by Yu-Jack** [comment]
“VirtualMachine” in “VirtualMachine generation is 2...” means that `this resource` is in k8s.  “Virtual Machine” means that we usually used it to describe about VM.  So, I suggest not to revise this word.

**Comment by asettle** [comment]
> “VirtualMachine” in “VirtualMachine generation is 2...” means that `this resource` is in k8s. “Virtual Machine” means that we usually used it to describe about VM. So, I suggest not to revise this word.

Hmm I understand. That being said, because it's the same text, it looks like a spelling mistake. Can we apply some mark-up to 'VirtualMachine' to ensure it's clear?

**Comment by a110605** [comment]
> > “VirtualMachine” in “VirtualMachine generation is 2...” means that `this resource` is in k8s. “Virtual Machine” means that we usually used it to describe about VM. So, I suggest not to revise this word.
> 
> Hmm I understand. That being said, because it's the same text, it looks like a spelling mistake. Can we apply some mark-up to 'VirtualMachine' to ensure it's clear?

Hi @Yu-Jack , could you help from backend side?

**Comment by Yu-Jack** [comment]
@a110605 Just like @FrankYang0529 mentioned, it's upstream code, we can't modify it. So, you probably need to handle it in frontend code for this specific case.

**Comment by a110605** [comment]
> > “VirtualMachine” in “VirtualMachine generation is 2...” means that `this resource` is in k8s. “Virtual Machine” means that we usually used it to describe about VM. So, I suggest not to revise this word.
> 
> Hmm I understand. That being said, because it's the same text, it looks like a spelling mistake. Can we apply some mark-up to 'VirtualMachine' to ensure it's clear?

Quick synced with  @Yu-Jack , we don't want to have any update in [generic.go]([harvester/vendor/sigs.k8s.io/cli-utils/pkg/kstatus/status/generic.go](https://github.com/harvester/harvester/blob/09fdcc538965fd0c3c4b8e2eb409b19d0b3dbdac/vendor/sigs.k8s.io/cli-utils/pkg/kstatus/status/generic.go#L90)) file, since it's upstream code. cc @bk201 

@asettle, can we skip this wording revision ?

**Comment by Yu-Jack** [comment]
BTW, that message is from https://github.com/kubernetes-sigs/cli-utils/blob/0a569f59bebe08eb86f0fb530741343b10e01249/pkg/kstatus/status/generic.go#L90.

**Comment by asettle** [comment]
> > > “VirtualMachine” in “VirtualMachine generation is 2...” means that `this resource` is in k8s. “Virtual Machine” means that we usually used it to describe about VM. So, I suggest not to revise this word.
> > 
> > 
> > Hmm I understand. That being said, because it's the same text, it looks like a spelling mistake. Can we apply some mark-up to 'VirtualMachine' to ensure it's clear?
> 
> Quick synced with @Yu-Jack , we don't want to have any change in [generic.go](%5Bharvester/vendor/sigs.k8s.io/cli-utils/pkg/kstatus/status/generic.go%5D(https://github.com/harvester/harvester/blob/09fdcc538965fd0c3c4b8e2eb409b19d0b3dbdac/vendor/sigs.k8s.io/cli-utils/pkg/kstatus/status/generic.go#L90)), since it's upstream code. cc @bk201
> 
> @asettle, can we skip this wording revision or we want to add specific logic in frontend to handle this wording ?

We can skip. It'll suffice for now. We can create a bug to handle this in later versions.

**Comment by a110605** [comment]
@asettle , I check [QA reported unfinished items ](https://github.com/harvester/harvester/issues/6407#issuecomment-2368993929)and seems we are still missing some items
 -  1). rancher monitoring (Addon: rancher-monitoring) is this Addon should be hyphenated ?
 -  3). Alert manager configs contradicts with Alert Manager configurations
 -  4).Logging (cluster Flow,cluster output,flow,output) contradicts with (cluster Flows.cluster Outputs,Flows,outputs) <- sorry, we should follow other resource to use plural wordings.
 - 6). Settings description (Typical users...) not changed as expected in the bug <- (should add new wording in harvester en-us.yaml)

 You can refer the my commits here : https://github.com/a110605/harvester-dashboard/commits/suggestion/

**Comment by asettle** [comment]
> * 3). Alert manager configs contradicts with Alert Manager configurations
https://github.com/harvester/dashboard/pull/1176/files#diff-c7b517e8422253bdca93e9c0d49cbecd98c42d0ef796342c9319078eaebfb1b7R1031 
> * 6). Settings description (Typical users...) not changed as expected in the bug <- (should add new wording in harvester en-us.yaml)

https://github.com/harvester/dashboard/pull/1176/files#diff-2f4699c41daff9d49b0ef303edbd950cc74e4b6baaf7f5cf46d30fa2fb1a6220R6958

> 
> You can refer the my commits here : https://github.com/a110605/harvester-dashboard/commits/suggestion/

**Review by a110605 — APPROVED** [review]
LGTM

**Pull request merged**
