### PR TITLE
HARVESTER: configure column min-width

### PR DESCRIPTION
**Pull request by DaiYuzeng**
#### PR Checklist
- ~Is this a multi-tenancy feature/bug?~
    - ~[ ] Yes, the relevant RBAC changes are at:~
- ~Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?~
    - ~[ ] Yes, the relevant PR is at:~
- ~Are backend engineers aware of UI changes?~
    - ~[ ] Yes, the backend owner is:~

### Occurred changes and/or fixed issues

- https://github.com/harvester/harvester/issues/3607

### CODE REVIEW

**Comment by WuJun2016** [comment]
@n313893254    Can you please take a look at whether the fix for this issue is appropriate today ?

**Review by n313893254 — CHANGES_REQUESTED** [review]
1920 × 1080：
image

2880 × 1800：
image


The host IP column is too short

**Comment by DaiYuzeng** [comment]
Do you have any ideas or suggestions? @n313893254 @WuJun2016 

I need to leave enough width of `CPU/Memory/Storage` column since it might be huge scale.

**Comment by WuJun2016** [comment]
@DaiYuzeng   Incorrect style
image

**Comment by WuJun2016** [comment]
> @DaiYuzeng Incorrect style image

sorry， This UX, let's file an issue to track it.

**Comment by WuJun2016** [comment]
> Do you have any ideas or suggestions? @n313893254 @WuJun2016
> 
> I need to leave enough width of `CPU/Memory/Storage` column since it might be huge scale.


https://github.com/harvester/dashboard/pull/704  @DaiYuzeng  PTAL.

**Comment by DaiYuzeng** [comment]
It's supposed that https://github.com/harvester/dashboard/pull/704 resolved this issue, so I am going to close this PR.

**Pull request closed without merging**
