### PR TITLE
HARVESTER: fix kvm disable warning message

### PR DESCRIPTION
**Pull request by WuJun2016**
### Summary
comment:  https://github.com/harvester/harvester/issues/3900#issuecomment-1550621856

#### PR Checklist
~- Is this a multi-tenancy feature/bug?~
    ~- [ ] Yes, the relevant RBAC changes are at:~
~- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?~
    ~- [ ] Yes, the relevant PR is at:~
~- Are backend engineers aware of UI changes?~
    ~- [ ] Yes, the backend owner is:~

Fixes #

- https://github.com/harvester/harvester/issues/3900#issuecomment-1550621856

### Occurred changes and/or fixed issues

When any of the following [conditions](https://github.com/harvester/harvester/issues/3900#issuecomment-1550621856) are met, we display an error message on the host details page。

image

### Technical notes summary

AMD and Intel machines, one of the annotations is false, or neither of the annotations exists, then we assume that `Hardware-based virtualization` is not enabled

### CODE REVIEW

**Comment by w13915984028** [comment]
Normally, it is `(hardware based) virtualization disabled by BIOS`, not `KVM disabled by BIOS`, KVM is a Linux kernel feature.

@WuJun2016  @bk201 lets update the warning message ?

e.g.
https://bce.berkeley.edu/enabling-virtualization-in-your-pc-bios.html

**Comment by bk201** [comment]
> Normally, it is `(hardware based) virtualization disabled by BIOS`, not `KVM disabled by BIOS`, KVM is a Linux kernel feature.
> 
> @WuJun2016 @bk201 lets update the warning message ?
> 
> e.g. https://bce.berkeley.edu/enabling-virtualization-in-your-pc-bios.html

+1, @WuJun2016 It's better to adjust the term to Hardware-based virtualization is disabled or not supported.

**Review by n313893254 — APPROVED** [review]
LGTM! Thanks

**Comment by n313893254** [comment]
@mergify backport release-harvester-v1.2

**Pull request merged**
