### PR TITLE
fix: honor annotation matchNodes from network config to show selected nodes in detail page

### PR DESCRIPTION
**Pull request by a110605**
### Summary

Per discussion this [comment](https://github.com/harvester/harvester/issues/5325#issuecomment-2236668074) with team, we decide to filter out witness node from backend annotation when creating network config via `select all nodes`.

Frontend only honors annoation `network.harvesterhci.io/matched-nodes` to show selected nodes in page.

Note. we will have backend PR to filter out witness node in `annotaton.network.harvesterhci.io/matched-nodes`.

#### PR Checklist
- Is this a multi-tenancy feature/bug?
    - [ ] Yes, the relevant RBAC changes are at:
- Do we need to backport changes to the [old Rancher UI](https://github.com/rancher/u), such as RKE1?
    - [ ] Yes, the relevant PR is at:
- Are backend engineers aware of UI changes?
    - [x] Yes, the backend owner is: @Vicente-Cheng 

Note. this PR needs backport to v1.3.1 and v1.4

Related Issue #
https://github.com/harvester/harvester/issues/5325

### Screenshot/Video
Screenshot_20240726_123218

### CODE REVIEW

**Comment by a110605** [comment]
Wait for[ backend PR](https://github.com/harvester/network-controller-harvester/pull/104#issuecomment-2259823066) merge first, then we can merge this PR

**Comment by a110605** [comment]
Test with latest harvester-network-controller. The witness node is filtered out in details list and YAML when select all nodes to create network config.

Screenshot_20240804_235845
Screenshot_20240804_235855

**Review by torchiaf — APPROVED** [review]
LGTM

**Comment by a110605** [comment]
@mergify backport release-harvester-v1.4

**Comment by a110605** [comment]
@mergify backport release-harvester-v1.3

**Pull request merged**
